/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;


public class AddressStringDigits extends BCDString {

	private static final long serialVersionUID = 1L;

	public AddressStringDigits() {
	}

	public AddressStringDigits(byte[] value) {
		super(value);
	}

}
