/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;


public class AdvisedChargeInformation implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 351);

	public byte[] code = null;
	private PaidIndicator paidIndicator = null;
	private PaymentMethod paymentMethod = null;
	private AdvisedChargeCurrency advisedChargeCurrency = null;
	private AdvisedCharge advisedCharge = null;
	private Commission commission = null;
	
	public AdvisedChargeInformation() {
	}

	public AdvisedChargeInformation(byte[] code) {
		this.code = code;
	}

	public void setPaidIndicator(PaidIndicator paidIndicator) {
		this.paidIndicator = paidIndicator;
	}

	public PaidIndicator getPaidIndicator() {
		return paidIndicator;
	}

	public void setPaymentMethod(PaymentMethod paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public PaymentMethod getPaymentMethod() {
		return paymentMethod;
	}

	public void setAdvisedChargeCurrency(AdvisedChargeCurrency advisedChargeCurrency) {
		this.advisedChargeCurrency = advisedChargeCurrency;
	}

	public AdvisedChargeCurrency getAdvisedChargeCurrency() {
		return advisedChargeCurrency;
	}

	public void setAdvisedCharge(AdvisedCharge advisedCharge) {
		this.advisedCharge = advisedCharge;
	}

	public AdvisedCharge getAdvisedCharge() {
		return advisedCharge;
	}

	public void setCommission(Commission commission) {
		this.commission = commission;
	}

	public Commission getCommission() {
		return commission;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (commission != null) {
			codeLength += commission.encode(reverseOS, true);
		}
		
		if (advisedCharge != null) {
			codeLength += advisedCharge.encode(reverseOS, true);
		}
		
		if (advisedChargeCurrency != null) {
			codeLength += advisedChargeCurrency.encode(reverseOS, true);
		}
		
		if (paymentMethod != null) {
			codeLength += paymentMethod.encode(reverseOS, true);
		}
		
		if (paidIndicator != null) {
			codeLength += paidIndicator.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(PaidIndicator.tag)) {
			paidIndicator = new PaidIndicator();
			subCodeLength += paidIndicator.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(PaymentMethod.tag)) {
			paymentMethod = new PaymentMethod();
			subCodeLength += paymentMethod.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(AdvisedChargeCurrency.tag)) {
			advisedChargeCurrency = new AdvisedChargeCurrency();
			subCodeLength += advisedChargeCurrency.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(AdvisedCharge.tag)) {
			advisedCharge = new AdvisedCharge();
			subCodeLength += advisedCharge.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(Commission.tag)) {
			commission = new Commission();
			subCodeLength += commission.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (paidIndicator != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("paidIndicator: ").append(paidIndicator);
			firstSelectedElement = false;
		}
		
		if (paymentMethod != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("paymentMethod: ").append(paymentMethod);
			firstSelectedElement = false;
		}
		
		if (advisedChargeCurrency != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("advisedChargeCurrency: ").append(advisedChargeCurrency);
			firstSelectedElement = false;
		}
		
		if (advisedCharge != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("advisedCharge: ").append(advisedCharge);
			firstSelectedElement = false;
		}
		
		if (commission != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("commission: ").append(commission);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

