/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;


public class Bid extends AsciiString {

	private static final long serialVersionUID = 1L;

	public Bid() {
	}

	public Bid(byte[] value) {
		super(value);
	}

}
