/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;


public class ChargedPartyInformation implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 324);

	public byte[] code = null;
	private ChargedPartyIdList chargedPartyIdList = null;
	private ChargedPartyHomeIdList chargedPartyHomeIdList = null;
	private ChargedPartyLocationList chargedPartyLocationList = null;
	private ChargedPartyEquipment chargedPartyEquipment = null;
	
	public ChargedPartyInformation() {
	}

	public ChargedPartyInformation(byte[] code) {
		this.code = code;
	}

	public void setChargedPartyIdList(ChargedPartyIdList chargedPartyIdList) {
		this.chargedPartyIdList = chargedPartyIdList;
	}

	public ChargedPartyIdList getChargedPartyIdList() {
		return chargedPartyIdList;
	}

	public void setChargedPartyHomeIdList(ChargedPartyHomeIdList chargedPartyHomeIdList) {
		this.chargedPartyHomeIdList = chargedPartyHomeIdList;
	}

	public ChargedPartyHomeIdList getChargedPartyHomeIdList() {
		return chargedPartyHomeIdList;
	}

	public void setChargedPartyLocationList(ChargedPartyLocationList chargedPartyLocationList) {
		this.chargedPartyLocationList = chargedPartyLocationList;
	}

	public ChargedPartyLocationList getChargedPartyLocationList() {
		return chargedPartyLocationList;
	}

	public void setChargedPartyEquipment(ChargedPartyEquipment chargedPartyEquipment) {
		this.chargedPartyEquipment = chargedPartyEquipment;
	}

	public ChargedPartyEquipment getChargedPartyEquipment() {
		return chargedPartyEquipment;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (chargedPartyEquipment != null) {
			codeLength += chargedPartyEquipment.encode(reverseOS, true);
		}
		
		if (chargedPartyLocationList != null) {
			codeLength += chargedPartyLocationList.encode(reverseOS, true);
		}
		
		if (chargedPartyHomeIdList != null) {
			codeLength += chargedPartyHomeIdList.encode(reverseOS, true);
		}
		
		if (chargedPartyIdList != null) {
			codeLength += chargedPartyIdList.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(ChargedPartyIdList.tag)) {
			chargedPartyIdList = new ChargedPartyIdList();
			subCodeLength += chargedPartyIdList.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ChargedPartyHomeIdList.tag)) {
			chargedPartyHomeIdList = new ChargedPartyHomeIdList();
			subCodeLength += chargedPartyHomeIdList.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ChargedPartyLocationList.tag)) {
			chargedPartyLocationList = new ChargedPartyLocationList();
			subCodeLength += chargedPartyLocationList.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ChargedPartyEquipment.tag)) {
			chargedPartyEquipment = new ChargedPartyEquipment();
			subCodeLength += chargedPartyEquipment.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (chargedPartyIdList != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargedPartyIdList: ");
			chargedPartyIdList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargedPartyHomeIdList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargedPartyHomeIdList: ");
			chargedPartyHomeIdList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargedPartyLocationList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargedPartyLocationList: ");
			chargedPartyLocationList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargedPartyEquipment != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargedPartyEquipment: ");
			chargedPartyEquipment.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

