/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;


public class ContentTransaction implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 17);

	public byte[] code = null;
	private ContentTransactionBasicInfo contentTransactionBasicInfo = null;
	private ChargedPartyInformation chargedPartyInformation = null;
	private ServingPartiesInformation servingPartiesInformation = null;
	private ContentServiceUsedList contentServiceUsed = null;
	private OperatorSpecInfoList operatorSpecInformation = null;
	
	public ContentTransaction() {
	}

	public ContentTransaction(byte[] code) {
		this.code = code;
	}

	public void setContentTransactionBasicInfo(ContentTransactionBasicInfo contentTransactionBasicInfo) {
		this.contentTransactionBasicInfo = contentTransactionBasicInfo;
	}

	public ContentTransactionBasicInfo getContentTransactionBasicInfo() {
		return contentTransactionBasicInfo;
	}

	public void setChargedPartyInformation(ChargedPartyInformation chargedPartyInformation) {
		this.chargedPartyInformation = chargedPartyInformation;
	}

	public ChargedPartyInformation getChargedPartyInformation() {
		return chargedPartyInformation;
	}

	public void setServingPartiesInformation(ServingPartiesInformation servingPartiesInformation) {
		this.servingPartiesInformation = servingPartiesInformation;
	}

	public ServingPartiesInformation getServingPartiesInformation() {
		return servingPartiesInformation;
	}

	public void setContentServiceUsed(ContentServiceUsedList contentServiceUsed) {
		this.contentServiceUsed = contentServiceUsed;
	}

	public ContentServiceUsedList getContentServiceUsed() {
		return contentServiceUsed;
	}

	public void setOperatorSpecInformation(OperatorSpecInfoList operatorSpecInformation) {
		this.operatorSpecInformation = operatorSpecInformation;
	}

	public OperatorSpecInfoList getOperatorSpecInformation() {
		return operatorSpecInformation;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (operatorSpecInformation != null) {
			codeLength += operatorSpecInformation.encode(reverseOS, true);
		}
		
		if (contentServiceUsed != null) {
			codeLength += contentServiceUsed.encode(reverseOS, true);
		}
		
		if (servingPartiesInformation != null) {
			codeLength += servingPartiesInformation.encode(reverseOS, true);
		}
		
		if (chargedPartyInformation != null) {
			codeLength += chargedPartyInformation.encode(reverseOS, true);
		}
		
		if (contentTransactionBasicInfo != null) {
			codeLength += contentTransactionBasicInfo.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(ContentTransactionBasicInfo.tag)) {
			contentTransactionBasicInfo = new ContentTransactionBasicInfo();
			subCodeLength += contentTransactionBasicInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ChargedPartyInformation.tag)) {
			chargedPartyInformation = new ChargedPartyInformation();
			subCodeLength += chargedPartyInformation.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ServingPartiesInformation.tag)) {
			servingPartiesInformation = new ServingPartiesInformation();
			subCodeLength += servingPartiesInformation.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ContentServiceUsedList.tag)) {
			contentServiceUsed = new ContentServiceUsedList();
			subCodeLength += contentServiceUsed.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(OperatorSpecInfoList.tag)) {
			operatorSpecInformation = new OperatorSpecInfoList();
			subCodeLength += operatorSpecInformation.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (contentTransactionBasicInfo != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("contentTransactionBasicInfo: ");
			contentTransactionBasicInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargedPartyInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargedPartyInformation: ");
			chargedPartyInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (servingPartiesInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("servingPartiesInformation: ");
			servingPartiesInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (contentServiceUsed != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("contentServiceUsed: ");
			contentServiceUsed.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (operatorSpecInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("operatorSpecInformation: ");
			operatorSpecInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

