/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;


public class DataInterChange implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public byte[] code = null;
	private TransferBatch transferBatch = null;
	private Notification notification = null;
	
	public DataInterChange() {
	}

	public DataInterChange(byte[] code) {
		this.code = code;
	}

	public void setTransferBatch(TransferBatch transferBatch) {
		this.transferBatch = transferBatch;
	}

	public TransferBatch getTransferBatch() {
		return transferBatch;
	}

	public void setNotification(Notification notification) {
		this.notification = notification;
	}

	public Notification getNotification() {
		return notification;
	}

	public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			return code.length;
		}

		int codeLength = 0;
		if (notification != null) {
			codeLength += notification.encode(reverseOS, true);
			return codeLength;
		}
		
		if (transferBatch != null) {
			codeLength += transferBatch.encode(reverseOS, true);
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int codeLength = 0;
		BerTag passedTag = berTag;

		if (berTag == null) {
			berTag = new BerTag();
			codeLength += berTag.decode(is);
		}

		if (berTag.equals(TransferBatch.tag)) {
			transferBatch = new TransferBatch();
			codeLength += transferBatch.decode(is, false);
			return codeLength;
		}

		if (berTag.equals(Notification.tag)) {
			notification = new Notification();
			codeLength += notification.decode(is, false);
			return codeLength;
		}

		if (passedTag != null) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (transferBatch != null) {
			sb.append("transferBatch: ");
			transferBatch.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (notification != null) {
			sb.append("notification: ");
			notification.appendAsString(sb, indentLevel + 1);
			return;
		}

		sb.append("<none>");
	}

}

