/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;
import com.beanit.jasn1.ber.types.string.*;


public class DataVolume extends BerInteger {

	private static final long serialVersionUID = 1L;

	public DataVolume() {
	}

	public DataVolume(byte[] code) {
		super(code);
	}

	public DataVolume(BigInteger value) {
		super(value);
	}

	public DataVolume(long value) {
		super(value);
	}

}
