/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.math.BigInteger;


public class DiscountValue extends AbsoluteAmount {

	private static final long serialVersionUID = 1L;

	public DiscountValue() {
	}

	public DiscountValue(byte[] code) {
		super(code);
	}

	public DiscountValue(BigInteger value) {
		super(value);
	}

	public DiscountValue(long value) {
		super(value);
	}

}
