/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;


public class LCSQosRequested implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 383);

	public byte[] code = null;
	private LCSRequestTimestamp lCSRequestTimestamp = null;
	private HorizontalAccuracyRequested horizontalAccuracyRequested = null;
	private VerticalAccuracyRequested verticalAccuracyRequested = null;
	private ResponseTimeCategory responseTimeCategory = null;
	private TrackingPeriod trackingPeriod = null;
	private TrackingFrequency trackingFrequency = null;
	
	public LCSQosRequested() {
	}

	public LCSQosRequested(byte[] code) {
		this.code = code;
	}

	public void setLCSRequestTimestamp(LCSRequestTimestamp lCSRequestTimestamp) {
		this.lCSRequestTimestamp = lCSRequestTimestamp;
	}

	public LCSRequestTimestamp getLCSRequestTimestamp() {
		return lCSRequestTimestamp;
	}

	public void setHorizontalAccuracyRequested(HorizontalAccuracyRequested horizontalAccuracyRequested) {
		this.horizontalAccuracyRequested = horizontalAccuracyRequested;
	}

	public HorizontalAccuracyRequested getHorizontalAccuracyRequested() {
		return horizontalAccuracyRequested;
	}

	public void setVerticalAccuracyRequested(VerticalAccuracyRequested verticalAccuracyRequested) {
		this.verticalAccuracyRequested = verticalAccuracyRequested;
	}

	public VerticalAccuracyRequested getVerticalAccuracyRequested() {
		return verticalAccuracyRequested;
	}

	public void setResponseTimeCategory(ResponseTimeCategory responseTimeCategory) {
		this.responseTimeCategory = responseTimeCategory;
	}

	public ResponseTimeCategory getResponseTimeCategory() {
		return responseTimeCategory;
	}

	public void setTrackingPeriod(TrackingPeriod trackingPeriod) {
		this.trackingPeriod = trackingPeriod;
	}

	public TrackingPeriod getTrackingPeriod() {
		return trackingPeriod;
	}

	public void setTrackingFrequency(TrackingFrequency trackingFrequency) {
		this.trackingFrequency = trackingFrequency;
	}

	public TrackingFrequency getTrackingFrequency() {
		return trackingFrequency;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (trackingFrequency != null) {
			codeLength += trackingFrequency.encode(reverseOS, true);
		}
		
		if (trackingPeriod != null) {
			codeLength += trackingPeriod.encode(reverseOS, true);
		}
		
		if (responseTimeCategory != null) {
			codeLength += responseTimeCategory.encode(reverseOS, true);
		}
		
		if (verticalAccuracyRequested != null) {
			codeLength += verticalAccuracyRequested.encode(reverseOS, true);
		}
		
		if (horizontalAccuracyRequested != null) {
			codeLength += horizontalAccuracyRequested.encode(reverseOS, true);
		}
		
		if (lCSRequestTimestamp != null) {
			codeLength += lCSRequestTimestamp.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(LCSRequestTimestamp.tag)) {
			lCSRequestTimestamp = new LCSRequestTimestamp();
			subCodeLength += lCSRequestTimestamp.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(HorizontalAccuracyRequested.tag)) {
			horizontalAccuracyRequested = new HorizontalAccuracyRequested();
			subCodeLength += horizontalAccuracyRequested.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(VerticalAccuracyRequested.tag)) {
			verticalAccuracyRequested = new VerticalAccuracyRequested();
			subCodeLength += verticalAccuracyRequested.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ResponseTimeCategory.tag)) {
			responseTimeCategory = new ResponseTimeCategory();
			subCodeLength += responseTimeCategory.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingPeriod.tag)) {
			trackingPeriod = new TrackingPeriod();
			subCodeLength += trackingPeriod.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingFrequency.tag)) {
			trackingFrequency = new TrackingFrequency();
			subCodeLength += trackingFrequency.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (lCSRequestTimestamp != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("lCSRequestTimestamp: ");
			lCSRequestTimestamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (horizontalAccuracyRequested != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("horizontalAccuracyRequested: ").append(horizontalAccuracyRequested);
			firstSelectedElement = false;
		}
		
		if (verticalAccuracyRequested != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("verticalAccuracyRequested: ").append(verticalAccuracyRequested);
			firstSelectedElement = false;
		}
		
		if (responseTimeCategory != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("responseTimeCategory: ").append(responseTimeCategory);
			firstSelectedElement = false;
		}
		
		if (trackingPeriod != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingPeriod: ").append(trackingPeriod);
			firstSelectedElement = false;
		}
		
		if (trackingFrequency != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingFrequency: ").append(trackingFrequency);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

