/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;


public class LCSQosDelivered implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 390);

	public byte[] code = null;
	private LCSTransactionStatus lCSTransactionStatus = null;
	private HorizontalAccuracyDelivered horizontalAccuracyDelivered = null;
	private VerticalAccuracyDelivered verticalAccuracyDelivered = null;
	private ResponseTime responseTime = null;
	private PositioningMethod positioningMethod = null;
	private TrackingPeriod trackingPeriod = null;
	private TrackingFrequency trackingFrequency = null;
	private AgeOfLocation ageOfLocation = null;
	
	public LCSQosDelivered() {
	}

	public LCSQosDelivered(byte[] code) {
		this.code = code;
	}

	public void setLCSTransactionStatus(LCSTransactionStatus lCSTransactionStatus) {
		this.lCSTransactionStatus = lCSTransactionStatus;
	}

	public LCSTransactionStatus getLCSTransactionStatus() {
		return lCSTransactionStatus;
	}

	public void setHorizontalAccuracyDelivered(HorizontalAccuracyDelivered horizontalAccuracyDelivered) {
		this.horizontalAccuracyDelivered = horizontalAccuracyDelivered;
	}

	public HorizontalAccuracyDelivered getHorizontalAccuracyDelivered() {
		return horizontalAccuracyDelivered;
	}

	public void setVerticalAccuracyDelivered(VerticalAccuracyDelivered verticalAccuracyDelivered) {
		this.verticalAccuracyDelivered = verticalAccuracyDelivered;
	}

	public VerticalAccuracyDelivered getVerticalAccuracyDelivered() {
		return verticalAccuracyDelivered;
	}

	public void setResponseTime(ResponseTime responseTime) {
		this.responseTime = responseTime;
	}

	public ResponseTime getResponseTime() {
		return responseTime;
	}

	public void setPositioningMethod(PositioningMethod positioningMethod) {
		this.positioningMethod = positioningMethod;
	}

	public PositioningMethod getPositioningMethod() {
		return positioningMethod;
	}

	public void setTrackingPeriod(TrackingPeriod trackingPeriod) {
		this.trackingPeriod = trackingPeriod;
	}

	public TrackingPeriod getTrackingPeriod() {
		return trackingPeriod;
	}

	public void setTrackingFrequency(TrackingFrequency trackingFrequency) {
		this.trackingFrequency = trackingFrequency;
	}

	public TrackingFrequency getTrackingFrequency() {
		return trackingFrequency;
	}

	public void setAgeOfLocation(AgeOfLocation ageOfLocation) {
		this.ageOfLocation = ageOfLocation;
	}

	public AgeOfLocation getAgeOfLocation() {
		return ageOfLocation;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (ageOfLocation != null) {
			codeLength += ageOfLocation.encode(reverseOS, true);
		}
		
		if (trackingFrequency != null) {
			codeLength += trackingFrequency.encode(reverseOS, true);
		}
		
		if (trackingPeriod != null) {
			codeLength += trackingPeriod.encode(reverseOS, true);
		}
		
		if (positioningMethod != null) {
			codeLength += positioningMethod.encode(reverseOS, true);
		}
		
		if (responseTime != null) {
			codeLength += responseTime.encode(reverseOS, true);
		}
		
		if (verticalAccuracyDelivered != null) {
			codeLength += verticalAccuracyDelivered.encode(reverseOS, true);
		}
		
		if (horizontalAccuracyDelivered != null) {
			codeLength += horizontalAccuracyDelivered.encode(reverseOS, true);
		}
		
		if (lCSTransactionStatus != null) {
			codeLength += lCSTransactionStatus.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(LCSTransactionStatus.tag)) {
			lCSTransactionStatus = new LCSTransactionStatus();
			subCodeLength += lCSTransactionStatus.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(HorizontalAccuracyDelivered.tag)) {
			horizontalAccuracyDelivered = new HorizontalAccuracyDelivered();
			subCodeLength += horizontalAccuracyDelivered.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(VerticalAccuracyDelivered.tag)) {
			verticalAccuracyDelivered = new VerticalAccuracyDelivered();
			subCodeLength += verticalAccuracyDelivered.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ResponseTime.tag)) {
			responseTime = new ResponseTime();
			subCodeLength += responseTime.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(PositioningMethod.tag)) {
			positioningMethod = new PositioningMethod();
			subCodeLength += positioningMethod.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingPeriod.tag)) {
			trackingPeriod = new TrackingPeriod();
			subCodeLength += trackingPeriod.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingFrequency.tag)) {
			trackingFrequency = new TrackingFrequency();
			subCodeLength += trackingFrequency.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(AgeOfLocation.tag)) {
			ageOfLocation = new AgeOfLocation();
			subCodeLength += ageOfLocation.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (lCSTransactionStatus != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("lCSTransactionStatus: ").append(lCSTransactionStatus);
			firstSelectedElement = false;
		}
		
		if (horizontalAccuracyDelivered != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("horizontalAccuracyDelivered: ").append(horizontalAccuracyDelivered);
			firstSelectedElement = false;
		}
		
		if (verticalAccuracyDelivered != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("verticalAccuracyDelivered: ").append(verticalAccuracyDelivered);
			firstSelectedElement = false;
		}
		
		if (responseTime != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("responseTime: ").append(responseTime);
			firstSelectedElement = false;
		}
		
		if (positioningMethod != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("positioningMethod: ").append(positioningMethod);
			firstSelectedElement = false;
		}
		
		if (trackingPeriod != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingPeriod: ").append(trackingPeriod);
			firstSelectedElement = false;
		}
		
		if (trackingFrequency != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingFrequency: ").append(trackingFrequency);
			firstSelectedElement = false;
		}
		
		if (ageOfLocation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("ageOfLocation: ").append(ageOfLocation);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

