/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;


public class LocationDescription extends AsciiString {

	private static final long serialVersionUID = 1L;

	public LocationDescription() {
	}

	public LocationDescription(byte[] value) {
		super(value);
	}

}
