/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;


public class NetworkId extends AsciiString {

	private static final long serialVersionUID = 1L;

	public NetworkId() {
	}

	public NetworkId(byte[] value) {
		super(value);
	}

}
