/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;


public class SupplServiceUsed implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 206);

	public byte[] code = null;
	private SupplServiceCode supplServiceCode = null;
	private SupplServiceActionCode supplServiceActionCode = null;
	private SsParameters ssParameters = null;
	private ChargingTimeStamp chargingTimeStamp = null;
	private ChargeInformation chargeInformation = null;
	private BasicServiceCodeList basicServiceCodeList = null;
	
	public SupplServiceUsed() {
	}

	public SupplServiceUsed(byte[] code) {
		this.code = code;
	}

	public void setSupplServiceCode(SupplServiceCode supplServiceCode) {
		this.supplServiceCode = supplServiceCode;
	}

	public SupplServiceCode getSupplServiceCode() {
		return supplServiceCode;
	}

	public void setSupplServiceActionCode(SupplServiceActionCode supplServiceActionCode) {
		this.supplServiceActionCode = supplServiceActionCode;
	}

	public SupplServiceActionCode getSupplServiceActionCode() {
		return supplServiceActionCode;
	}

	public void setSsParameters(SsParameters ssParameters) {
		this.ssParameters = ssParameters;
	}

	public SsParameters getSsParameters() {
		return ssParameters;
	}

	public void setChargingTimeStamp(ChargingTimeStamp chargingTimeStamp) {
		this.chargingTimeStamp = chargingTimeStamp;
	}

	public ChargingTimeStamp getChargingTimeStamp() {
		return chargingTimeStamp;
	}

	public void setChargeInformation(ChargeInformation chargeInformation) {
		this.chargeInformation = chargeInformation;
	}

	public ChargeInformation getChargeInformation() {
		return chargeInformation;
	}

	public void setBasicServiceCodeList(BasicServiceCodeList basicServiceCodeList) {
		this.basicServiceCodeList = basicServiceCodeList;
	}

	public BasicServiceCodeList getBasicServiceCodeList() {
		return basicServiceCodeList;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (basicServiceCodeList != null) {
			codeLength += basicServiceCodeList.encode(reverseOS, true);
		}
		
		if (chargeInformation != null) {
			codeLength += chargeInformation.encode(reverseOS, true);
		}
		
		if (chargingTimeStamp != null) {
			codeLength += chargingTimeStamp.encode(reverseOS, true);
		}
		
		if (ssParameters != null) {
			codeLength += ssParameters.encode(reverseOS, true);
		}
		
		if (supplServiceActionCode != null) {
			codeLength += supplServiceActionCode.encode(reverseOS, true);
		}
		
		if (supplServiceCode != null) {
			codeLength += supplServiceCode.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(SupplServiceCode.tag)) {
			supplServiceCode = new SupplServiceCode();
			subCodeLength += supplServiceCode.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(SupplServiceActionCode.tag)) {
			supplServiceActionCode = new SupplServiceActionCode();
			subCodeLength += supplServiceActionCode.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(SsParameters.tag)) {
			ssParameters = new SsParameters();
			subCodeLength += ssParameters.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ChargingTimeStamp.tag)) {
			chargingTimeStamp = new ChargingTimeStamp();
			subCodeLength += chargingTimeStamp.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ChargeInformation.tag)) {
			chargeInformation = new ChargeInformation();
			subCodeLength += chargeInformation.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BasicServiceCodeList.tag)) {
			basicServiceCodeList = new BasicServiceCodeList();
			subCodeLength += basicServiceCodeList.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (supplServiceCode != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("supplServiceCode: ").append(supplServiceCode);
			firstSelectedElement = false;
		}
		
		if (supplServiceActionCode != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("supplServiceActionCode: ").append(supplServiceActionCode);
			firstSelectedElement = false;
		}
		
		if (ssParameters != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("ssParameters: ").append(ssParameters);
			firstSelectedElement = false;
		}
		
		if (chargingTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargingTimeStamp: ");
			chargingTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargeInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargeInformation: ");
			chargeInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (basicServiceCodeList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("basicServiceCodeList: ");
			basicServiceCodeList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

