/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;


public class TrackedCustomerInformation implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 367);

	public byte[] code = null;
	private TrackedCustomerIdList trackedCustomerIdList = null;
	private TrackedCustomerHomeIdList trackedCustomerHomeIdList = null;
	private TrackedCustomerLocList trackedCustomerLocList = null;
	private TrackedCustomerEquipment trackedCustomerEquipment = null;
	
	public TrackedCustomerInformation() {
	}

	public TrackedCustomerInformation(byte[] code) {
		this.code = code;
	}

	public void setTrackedCustomerIdList(TrackedCustomerIdList trackedCustomerIdList) {
		this.trackedCustomerIdList = trackedCustomerIdList;
	}

	public TrackedCustomerIdList getTrackedCustomerIdList() {
		return trackedCustomerIdList;
	}

	public void setTrackedCustomerHomeIdList(TrackedCustomerHomeIdList trackedCustomerHomeIdList) {
		this.trackedCustomerHomeIdList = trackedCustomerHomeIdList;
	}

	public TrackedCustomerHomeIdList getTrackedCustomerHomeIdList() {
		return trackedCustomerHomeIdList;
	}

	public void setTrackedCustomerLocList(TrackedCustomerLocList trackedCustomerLocList) {
		this.trackedCustomerLocList = trackedCustomerLocList;
	}

	public TrackedCustomerLocList getTrackedCustomerLocList() {
		return trackedCustomerLocList;
	}

	public void setTrackedCustomerEquipment(TrackedCustomerEquipment trackedCustomerEquipment) {
		this.trackedCustomerEquipment = trackedCustomerEquipment;
	}

	public TrackedCustomerEquipment getTrackedCustomerEquipment() {
		return trackedCustomerEquipment;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (trackedCustomerEquipment != null) {
			codeLength += trackedCustomerEquipment.encode(reverseOS, true);
		}
		
		if (trackedCustomerLocList != null) {
			codeLength += trackedCustomerLocList.encode(reverseOS, true);
		}
		
		if (trackedCustomerHomeIdList != null) {
			codeLength += trackedCustomerHomeIdList.encode(reverseOS, true);
		}
		
		if (trackedCustomerIdList != null) {
			codeLength += trackedCustomerIdList.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(TrackedCustomerIdList.tag)) {
			trackedCustomerIdList = new TrackedCustomerIdList();
			subCodeLength += trackedCustomerIdList.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackedCustomerHomeIdList.tag)) {
			trackedCustomerHomeIdList = new TrackedCustomerHomeIdList();
			subCodeLength += trackedCustomerHomeIdList.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackedCustomerLocList.tag)) {
			trackedCustomerLocList = new TrackedCustomerLocList();
			subCodeLength += trackedCustomerLocList.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackedCustomerEquipment.tag)) {
			trackedCustomerEquipment = new TrackedCustomerEquipment();
			subCodeLength += trackedCustomerEquipment.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (trackedCustomerIdList != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerIdList: ");
			trackedCustomerIdList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (trackedCustomerHomeIdList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerHomeIdList: ");
			trackedCustomerHomeIdList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (trackedCustomerLocList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerLocList: ");
			trackedCustomerLocList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (trackedCustomerEquipment != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerEquipment: ");
			trackedCustomerEquipment.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

