/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.tap;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;


public class TransferBatch implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 1);

	public byte[] code = null;
	private BatchControlInfo batchControlInfo = null;
	private AccountingInfo accountingInfo = null;
	private NetworkInfo networkInfo = null;
	private MessageDescriptionInfoList messageDescriptionInfo = null;
	private CallEventDetailList callEventDetails = null;
	private AuditControlInfo auditControlInfo = null;
	
	public TransferBatch() {
	}

	public TransferBatch(byte[] code) {
		this.code = code;
	}

	public void setBatchControlInfo(BatchControlInfo batchControlInfo) {
		this.batchControlInfo = batchControlInfo;
	}

	public BatchControlInfo getBatchControlInfo() {
		return batchControlInfo;
	}

	public void setAccountingInfo(AccountingInfo accountingInfo) {
		this.accountingInfo = accountingInfo;
	}

	public AccountingInfo getAccountingInfo() {
		return accountingInfo;
	}

	public void setNetworkInfo(NetworkInfo networkInfo) {
		this.networkInfo = networkInfo;
	}

	public NetworkInfo getNetworkInfo() {
		return networkInfo;
	}

	public void setMessageDescriptionInfo(MessageDescriptionInfoList messageDescriptionInfo) {
		this.messageDescriptionInfo = messageDescriptionInfo;
	}

	public MessageDescriptionInfoList getMessageDescriptionInfo() {
		return messageDescriptionInfo;
	}

	public void setCallEventDetails(CallEventDetailList callEventDetails) {
		this.callEventDetails = callEventDetails;
	}

	public CallEventDetailList getCallEventDetails() {
		return callEventDetails;
	}

	public void setAuditControlInfo(AuditControlInfo auditControlInfo) {
		this.auditControlInfo = auditControlInfo;
	}

	public AuditControlInfo getAuditControlInfo() {
		return auditControlInfo;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (auditControlInfo != null) {
			codeLength += auditControlInfo.encode(reverseOS, true);
		}
		
		if (callEventDetails != null) {
			codeLength += callEventDetails.encode(reverseOS, true);
		}
		
		if (messageDescriptionInfo != null) {
			codeLength += messageDescriptionInfo.encode(reverseOS, true);
		}
		
		if (networkInfo != null) {
			codeLength += networkInfo.encode(reverseOS, true);
		}
		
		if (accountingInfo != null) {
			codeLength += accountingInfo.encode(reverseOS, true);
		}
		
		if (batchControlInfo != null) {
			codeLength += batchControlInfo.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(BatchControlInfo.tag)) {
			batchControlInfo = new BatchControlInfo();
			subCodeLength += batchControlInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(AccountingInfo.tag)) {
			accountingInfo = new AccountingInfo();
			subCodeLength += accountingInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(NetworkInfo.tag)) {
			networkInfo = new NetworkInfo();
			subCodeLength += networkInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(MessageDescriptionInfoList.tag)) {
			messageDescriptionInfo = new MessageDescriptionInfoList();
			subCodeLength += messageDescriptionInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(CallEventDetailList.tag)) {
			callEventDetails = new CallEventDetailList();
			subCodeLength += callEventDetails.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(AuditControlInfo.tag)) {
			auditControlInfo = new AuditControlInfo();
			subCodeLength += auditControlInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (batchControlInfo != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("batchControlInfo: ");
			batchControlInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (accountingInfo != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountingInfo: ");
			accountingInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (networkInfo != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("networkInfo: ");
			networkInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (messageDescriptionInfo != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("messageDescriptionInfo: ");
			messageDescriptionInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (callEventDetails != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("callEventDetails: ");
			callEventDetails.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (auditControlInfo != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("auditControlInfo: ");
			auditControlInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

